title: "Nuno Oliveira Fernandes"
description: "Full-Stack Software Engineer & Master's Student"
url: "https://nof03.github.io"
baseurl: ""

# Personal Info
author:
  name: "Nuno Oliveira Fernandes"
  email: "nuno.o.fernandes@outlook.pt"
  phone: "961 789 636"
  linkedin: "nuno-nof-fernandes"
  github: "NOF03"
  location: "Madeira/Porto"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge
